# Generated by Django 3.0.3 on 2021-03-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_healthfacilitycatchment_healthfacilitylegalform_healthfacilitymutation_healthfacilitysublevel'),
        ('product', '__first__'),
        ('claim_batch', '0001_initial'),
    ]

    operations = []
