# Generated by Django 3.0.3 on 2021-03-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim_batch', '0002_capitationpayment'),
    ]

    operations = [
    ]
