# Generated by Django 3.2.18 on 2023-05-15 11:55

from django.db import migrations, models
import django.db.models.deletion
from claim_batch.services import ProcessBatchSubmit, ProcessBatchService
from concurrent.futures import ThreadPoolExecutor
from core.utils import filter_validity


def add_previous_batch_run_catpitaion_payment_entries(apps, schema_editor):
    BatchRun = apps.get_model('claim_batch', 'BatchRun')
    service = ProcessBatchService(None)
    batch_runs = BatchRun.objects.filter(*filter_validity()).values(
        'location', 'run_year', 'run_month').all()
    with ThreadPoolExecutor(max_workers=30) as executor:
        for run in batch_runs:
            submit = ProcessBatchSubmit(
                location_id=run['location'],
                year=run['run_year'],
                month=run['run_month'],
            )
            executor.submit(service.capitation_report_data_for_summit, submit)


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_auto_20230317_1534'),
        ('product', '0006_insert_ceiling_type'),
        ('claim_batch', '0006_capitationpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrun',
            name='location',
            field=models.ForeignKey(blank=True, db_column='LocationId', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='location.location'),
        ),
        migrations.AddField(
            model_name='relativedistribution',
            name='product',
            field=models.ForeignKey(db_column='ProdID', on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='relative_distributions', to='product.product'),
        ),
        migrations.AddField(
            model_name='relativeindex',
            name='location',
            field=models.ForeignKey(blank=True, db_column='LocationId', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='relative_indexes', to='location.location'),
        ),
        migrations.AddField(
            model_name='relativeindex',
            name='product',
            field=models.ForeignKey(
                db_column='ProdID', on_delete=django.db.models.deletion.DO_NOTHING, to='product.product'),
        ),
        migrations.AlterField(
            model_name='relativedistribution',
            name='care_type',
            field=models.CharField(choices=[('B', 'Both'), ('I', 'In-Patient'),
                                   ('O', 'Out-Patient')], db_column='DistrCareType', max_length=1),
        ),
        migrations.AlterField(
            model_name='relativedistribution',
            name='type',
            field=models.SmallIntegerField(
                choices=[(12, 'Month'), (4, 'Quarter'), (1, 'Year')], db_column='DistrType'),
        ),
        migrations.RunPython(add_previous_batch_run_catpitaion_payment_entries,
                             reverse_code=migrations.RunPython.noop)
    ]
