# Generated by Django 4.2 on 2026-07-07 13:06

import claim_batch.models
import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid6
import logging
from django.db.models import Func, F
from django.db.models.fields import UUIDField
from django.apps import apps as global_apps
from django.contrib.contenttypes.management import create_contenttypes

logger = logging.getLogger(__name__)
location_ct = None


class RandomUUID(Func):
    """Cross-database random UUID for Django 4.2"""
    function = None  # Will be overridden per backend
    output_field = UUIDField()
    arity = 0

    def as_postgresql(self, compiler, connection, **extra_context):
        # PostgreSQL 13+ has gen_random_uuid() built-in
        return self.as_sql(compiler, connection, function='gen_random_uuid', **extra_context)

    def as_microsoft(self, compiler, connection, **extra_context):  # MSSQL
        return self.as_sql(compiler, connection, function='NEWID', **extra_context)

    # Optional: fallback for other DBs (e.g. SQLite for dev)
    def as_sql(self, compiler, connection, **extra_context):
        # if connection.vendor == 'postgresql':
        #     return self.as_postgresql(compiler, connection, **extra_context)
        # elif connection.vendor in ('microsoft', 'mssql'):
        #     return self.as_microsoft(compiler, connection, **extra_context)
        if extra_context.get('function', self.function) is None:
            # You can raise or use a default
            raise NotImplementedError(f"RandomUUID not supported on {connection.vendor}")
        return super().as_sql(compiler, connection, **extra_context)

def populate_scope_type(apps, schema_editor):

    BatchRun = apps.get_model('claim_batch', 'BatchRun')
    RelativeIndex = apps.get_model('claim_batch', 'RelativeIndex')
    location_ct = get_location_ct(apps)
    if location_ct:
        BatchRun.objects.update(scope_type=location_ct, scope_id=F('location_id'), uuid=RandomUUID())
        RelativeIndex.objects.update(scope_type=location_ct, scope_id=F('location_id'), uuid=RandomUUID())


def get_location_ct(apps):
    global location_ct
    app_config = global_apps.get_app_config('location')  # your app name
    create_contenttypes(app_config, verbosity=0)
    ContentType = apps.get_model('contenttypes', 'ContentType')
    try:
        location_ct = ContentType.objects.get(app_label='location', model='location')
    except ContentType.DoesNotExist:
        logger.warn("Location ContentType not found! likely initial migration with no data")
    return location_ct


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("claim_batch", "0008_set_managed_to_true"),
        ('location', '0013_auto_20230317_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchrun",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="batchrun",
            name="validity_from",
        ),
        migrations.RemoveField(
            model_name="batchrun",
            name="validity_to",
        ),
        migrations.RemoveField(
            model_name="relativeindex",
            name="legacy_id",
        ),

        migrations.RemoveField(
            model_name="relativeindex",
            name="validity_from",
        ),
        migrations.RemoveField(
            model_name="relativeindex",
            name="validity_to",
        ),
        migrations.AddField(
            model_name="batchrun",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="batchrun",
            name="date_deactivated",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="batchrun",
            name="json_ext",
            field=models.JSONField(blank=True, db_column="Json_ext", null=True),
        ),
        migrations.AddField(
            model_name="batchrun",
            name="scope_id",
            field=models.CharField(
                blank=True, db_column="ScopeId", max_length=255, null=True
            ),
        ),

        migrations.AddField(
            model_name="batchrun",
            name="scope_type",
            field=models.ForeignKey(
                db_column="ScopeType",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="batchrun",
            name="uuid",
            field=models.UUIDField(
                db_column="UUID",
                default=uuid6.uuid7,
                editable=False,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="batchrun",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="relativeindex",
            name="uuid",
            field=models.UUIDField(
                db_column="UUID", default=uuid6.uuid7, editable=False, unique=True
            ),
        ),
         migrations.AddField(
            model_name="relativeindex",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="relativeindex",
            name="date_deactivated",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="relativeindex",
            name="json_ext",
            field=models.JSONField(blank=True, db_column="Json_ext", null=True),
        ),
        migrations.AddField(
            model_name="relativeindex",
            name="scope_id",
            field=models.CharField(
                blank=True, db_column="ScopeId", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="relativeindex",
            name="scope_type",
            field=models.ForeignKey(
                db_column="ScopeType",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="contenttypes.contenttype",
            ),
        ),

        migrations.AddField(
            model_name="relativeindex",
            name="version",
            field=models.IntegerField(default=1),
        ),

        migrations.RunPython(populate_scope_type, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="batchrun",
            name="location",
        ),
                migrations.RemoveField(
            model_name="relativeindex",
            name="location",
        ),
        migrations.AlterField(
            model_name="batchrun",
            name="scope_type",
            field=models.ForeignKey(
                db_column="ScopeType",
                default=claim_batch.models.get_location_content_type_id,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="relativeindex",
            name="scope_type",
            field=models.ForeignKey(
                db_column="ScopeType",
                default=claim_batch.models.get_location_content_type_id,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="contenttypes.contenttype",
            ),
        ),

        migrations.CreateModel(
            name="HistoricalBatchRun",
            fields=[
                ("version", models.IntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                (
                    "json_ext",
                    models.JSONField(blank=True, db_column="Json_ext", null=True),
                ),
                ("date_deactivated", models.DateTimeField(default=None, null=True)),
                (
                    "id",
                    models.IntegerField(blank=True, db_column="RunID", db_index=True),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_column="UUID",
                        db_index=True,
                        default=uuid6.uuid7,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "scope_id",
                    models.CharField(
                        blank=True, db_column="ScopeId", max_length=255, null=True
                    ),
                ),
                ("run_date", core.fields.DateTimeField(db_column="RunDate")),
                ("audit_user_id", models.IntegerField(db_column="AuditUserID")),
                ("run_year", models.IntegerField(db_column="RunYear")),
                ("run_month", models.SmallIntegerField(db_column="RunMonth")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scope_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="ScopeType",
                        db_constraint=False,
                        default=claim_batch.models.get_location_content_type_id,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical batch run",
                "verbose_name_plural": "historical batch runs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        
       

        migrations.CreateModel(
            name="HistoricalRelativeIndex",
            fields=[
                ("version", models.IntegerField(default=1)),
                (
                    "uuid",
                    models.UUIDField(
                        db_column="UUID",
                        db_index=True,
                        default=uuid6.uuid7,
                        editable=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "json_ext",
                    models.JSONField(blank=True, db_column="Json_ext", null=True),
                ),
                ("date_deactivated", models.DateTimeField(default=None, null=True)),
                (
                    "id",
                    models.IntegerField(
                        blank=True, db_column="RelIndexID", db_index=True
                    ),
                ),
                ("type", models.SmallIntegerField(db_column="RelType")),
                ("care_type", models.CharField(db_column="RelCareType", max_length=1)),
                ("year", models.IntegerField(db_column="RelYear")),
                ("period", models.SmallIntegerField(db_column="RelPeriod")),
                ("calc_date", models.DateTimeField(db_column="CalcDate")),
                (
                    "rel_index",
                    models.DecimalField(
                        blank=True,
                        db_column="RelIndex",
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("audit_user_id", models.IntegerField(db_column="AuditUserID")),
                (
                    "scope_id",
                    models.CharField(
                        blank=True, db_column="ScopeId", max_length=255, null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_column="ProdID",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="product.product",
                    ),
                ),
                (
                    "scope_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="ScopeType",
                        db_constraint=False,
                        default=claim_batch.models.get_location_content_type_id,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical relative index",
                "verbose_name_plural": "historical relative indexs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
